import type {
  ActivityEntry,
  AppNotification,
  Assignment,
  Conversation,
  LinkedAccount,
  Message,
  NotificationPrefs,
  Photographer,
  Post,
  PrivacySettings,
  VerificationRequest,
} from './types'
import { formatTime12, isoFromToday } from './date'
// Feed photography — Unsplash, free to use under the Unsplash licence.
import coastlineSunrise from '../assets/posts/coastline-sunrise.jpg'
import forestMonsoon from '../assets/posts/forest-monsoon.jpg'
import mountainsDusk from '../assets/posts/mountains-dusk.jpg'
import resortDusk from '../assets/posts/resort-dusk.jpg'
import weddingGoldenHour from '../assets/posts/wedding-goldenhour.jpg'

export const photographers: Photographer[] = [
  {
    id: 'p1',
    name: 'Ananya Rao',
    handle: '@ananyashoots',
    gradient: 'from-indigo-500 to-violet-600',
    city: 'Udaipur',
    state: 'Rajasthan',
    bio: 'Destination wedding shooter working across Rajasthan for 8 years. Comfortable with large family setups and low-light mandap coverage.',
    specialties: ['Wedding', 'Portrait', 'Candid'],
    proficiency: 'Expert',
    dayRate: 18000,
    rating: 4.9,
    timesHired: 64,
    assignmentCount: 71,
    followers: 4820,
    respondsIn: 'under 2 hrs',
    equipment: [
      { category: 'Cameras', items: ['Sony A7 IV', 'Sony A7 III (backup)'] },
      { category: 'Lenses', items: ['24-70mm f/2.8 GM', '85mm f/1.4 GM', '35mm f/1.8'] },
      { category: 'Lighting', items: ['Godox AD200 Pro x2', 'Softbox + stands'] },
    ],
    recentWork: [
      { id: 'w1', title: 'Jagmandir Wedding', gradient: 'from-amber-500 to-rose-600' },
      { id: 'w2', title: 'Haveli Portraits', gradient: 'from-indigo-500 to-purple-600' },
      { id: 'w3', title: 'Sangeet Night', gradient: 'from-fuchsia-500 to-pink-600' },
      { id: 'w4', title: 'Lake Pichola', gradient: 'from-sky-500 to-blue-600' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Vikram Sethi',
        authorGradient: 'from-emerald-500 to-teal-600',
        rating: 5,
        daysAgo: 6,
        text: 'Flew her in on 12 hours notice when my second shooter fell ill. Delivered better frames than my primary. Absolute professional.',
      },
      {
        id: 'r2',
        author: 'Meera Joshi',
        authorGradient: 'from-orange-500 to-red-600',
        rating: 5,
        daysAgo: 24,
        text: 'Knows every good light pocket in Udaipur. Saved us hours of scouting.',
      },
    ],
    occupiedDates: [2, 3, 4, 11, 12, 19, 25, 26].map(isoFromToday),
  },
  {
    id: 'p2',
    name: 'Rohan Mehta',
    handle: '@rohanaerials',
    gradient: 'from-sky-500 to-cyan-600',
    city: 'Goa',
    state: 'Goa',
    bio: 'Licensed drone pilot and aerial cinematographer. DGCA certified, insured rig, happy to travel at short notice.',
    specialties: ['Drone', 'Aerial', 'Travel'],
    proficiency: 'Expert',
    dayRate: 22000,
    rating: 4.8,
    timesHired: 41,
    assignmentCount: 46,
    followers: 3110,
    respondsIn: 'under 1 hr',
    equipment: [
      { category: 'Drones', items: ['DJI Mavic 3 Pro', 'DJI Mini 4 Pro (backup)'] },
      { category: 'Cameras', items: ['Canon R6 Mark II'] },
      { category: 'Support', items: ['DJI RS 3 gimbal', 'ND filter set'] },
    ],
    recentWork: [
      { id: 'w1', title: 'Dudhsagar Falls', gradient: 'from-emerald-500 to-green-600' },
      { id: 'w2', title: 'Coastline Reel', gradient: 'from-cyan-500 to-blue-600' },
      { id: 'w3', title: 'Resort Campaign', gradient: 'from-amber-500 to-orange-600' },
      { id: 'w4', title: 'Beach Wedding', gradient: 'from-rose-500 to-pink-600' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Kabir Nair',
        authorGradient: 'from-violet-500 to-indigo-600',
        rating: 5,
        daysAgo: 11,
        text: 'My drone went down the day before a resort shoot. Rohan drove three hours and covered the whole aerial package.',
      },
    ],
    occupiedDates: [1, 6, 7, 8, 15, 22, 23].map(isoFromToday),
  },
  {
    id: 'p3',
    name: 'Priya Nambiar',
    handle: '@priyawild',
    gradient: 'from-emerald-500 to-teal-600',
    city: 'Kochi',
    state: 'Kerala',
    bio: 'Wildlife and documentary photographer. Long lens specialist, used to early calls and rough terrain.',
    specialties: ['Wildlife', 'Documentary', 'Landscape'],
    proficiency: 'Advanced',
    dayRate: 14000,
    rating: 4.7,
    timesHired: 28,
    assignmentCount: 33,
    followers: 1960,
    respondsIn: 'under 4 hrs',
    equipment: [
      { category: 'Cameras', items: ['Nikon Z8', 'Nikon D850'] },
      { category: 'Lenses', items: ['200-500mm f/5.6', '70-200mm f/2.8', '24-120mm f/4'] },
      { category: 'Support', items: ['Gitzo tripod', 'Gimbal head'] },
    ],
    recentWork: [
      { id: 'w1', title: 'Periyar Reserve', gradient: 'from-green-500 to-emerald-700' },
      { id: 'w2', title: 'Backwater Series', gradient: 'from-teal-500 to-cyan-600' },
      { id: 'w3', title: 'Monsoon Birds', gradient: 'from-slate-500 to-slate-700' },
      { id: 'w4', title: 'Fisherfolk', gradient: 'from-amber-500 to-yellow-600' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Arjun Das',
        authorGradient: 'from-blue-500 to-indigo-600',
        rating: 5,
        daysAgo: 3,
        text: 'Patient, quiet, and reads animal behaviour better than anyone I have worked with.',
      },
      {
        id: 'r2',
        author: 'Sneha Pillai',
        authorGradient: 'from-pink-500 to-rose-600',
        rating: 4,
        daysAgo: 40,
        text: 'Great in the field. Delivery took a few days longer than promised.',
      },
    ],
    occupiedDates: [5, 9, 10, 17, 18, 29].map(isoFromToday),
  },
  {
    id: 'p4',
    name: 'Devansh Kapoor',
    handle: '@devanshframes',
    gradient: 'from-orange-500 to-red-600',
    city: 'Jaipur',
    state: 'Rajasthan',
    bio: 'Second shooter and lighting assistant turning primary. Fast on setup, reliable on long event days.',
    specialties: ['Event', 'Wedding', 'Product'],
    proficiency: 'Intermediate',
    dayRate: 8500,
    rating: 4.5,
    timesHired: 17,
    assignmentCount: 19,
    followers: 740,
    respondsIn: 'under 6 hrs',
    equipment: [
      { category: 'Cameras', items: ['Canon R7', 'Canon 90D'] },
      { category: 'Lenses', items: ['18-55mm', '50mm f/1.8', '70-200mm f/4'] },
      { category: 'Lighting', items: ['Godox SL60W', 'Reflector kit'] },
    ],
    recentWork: [
      { id: 'w1', title: 'Amber Fort Shoot', gradient: 'from-amber-500 to-orange-600' },
      { id: 'w2', title: 'Corporate Offsite', gradient: 'from-blue-500 to-indigo-600' },
      { id: 'w3', title: 'Jewellery Catalog', gradient: 'from-yellow-500 to-amber-600' },
      { id: 'w4', title: 'Reception', gradient: 'from-rose-500 to-red-600' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Ananya Rao',
        authorGradient: 'from-indigo-500 to-violet-600',
        rating: 5,
        daysAgo: 15,
        text: 'Hired him as second shooter twice this season. Never had to repeat an instruction.',
      },
    ],
    occupiedDates: [0, 1, 13, 14, 20, 27, 28].map(isoFromToday),
  },
  {
    id: 'p5',
    name: 'Simran Kaur',
    handle: '@simranstudio',
    gradient: 'from-fuchsia-500 to-pink-600',
    city: 'Mumbai',
    state: 'Maharashtra',
    bio: 'Fashion and editorial photographer. Studio in Andheri, full lighting setup, comfortable directing talent.',
    specialties: ['Fashion', 'Editorial', 'Portrait'],
    proficiency: 'Expert',
    dayRate: 26000,
    rating: 4.9,
    timesHired: 52,
    assignmentCount: 58,
    followers: 6740,
    respondsIn: 'under 3 hrs',
    equipment: [
      { category: 'Cameras', items: ['Canon R5', 'Hasselblad X2D (rental)'] },
      { category: 'Lenses', items: ['85mm f/1.2', '50mm f/1.2', '24-70mm f/2.8'] },
      { category: 'Lighting', items: ['Profoto B10 x3', 'Octabox', 'Strip boxes'] },
    ],
    recentWork: [
      { id: 'w1', title: 'Resort 26 Lookbook', gradient: 'from-pink-500 to-fuchsia-600' },
      { id: 'w2', title: 'Beauty Editorial', gradient: 'from-purple-500 to-violet-600' },
      { id: 'w3', title: 'Menswear Campaign', gradient: 'from-slate-500 to-zinc-700' },
      { id: 'w4', title: 'Cover Shoot', gradient: 'from-red-500 to-rose-600' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Tara Menon',
        authorGradient: 'from-cyan-500 to-sky-600',
        rating: 5,
        daysAgo: 9,
        text: 'Took over a campaign mid-shoot when the original lead had a family emergency. Client never noticed the switch.',
      },
    ],
    occupiedDates: [2, 3, 8, 16, 21, 24, 30].map(isoFromToday),
  },
  {
    id: 'p6',
    name: 'Tenzin Wangdu',
    handle: '@tenzinhighaltitude',
    gradient: 'from-blue-500 to-indigo-600',
    city: 'Leh',
    state: 'Ladakh',
    bio: 'High-altitude and expedition photographer based in Leh. Acclimatised, own vehicle, works down to -20°C.',
    specialties: ['Landscape', 'Travel', 'Expedition'],
    proficiency: 'Advanced',
    dayRate: 12000,
    rating: 4.8,
    timesHired: 22,
    assignmentCount: 25,
    followers: 2380,
    respondsIn: 'under 12 hrs',
    equipment: [
      { category: 'Cameras', items: ['Fujifilm GFX 100S', 'Fujifilm X-T5'] },
      { category: 'Lenses', items: ['23mm f/4', '32-64mm f/4', '100-200mm f/5.6'] },
      { category: 'Support', items: ['Carbon tripod', 'Solar charging kit'] },
    ],
    recentWork: [
      { id: 'w1', title: 'Pangong Winter', gradient: 'from-sky-500 to-blue-700' },
      { id: 'w2', title: 'Nubra Dunes', gradient: 'from-amber-500 to-orange-700' },
      { id: 'w3', title: 'Monastery Series', gradient: 'from-red-500 to-rose-700' },
      { id: 'w4', title: 'Khardung La', gradient: 'from-slate-400 to-slate-700' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Rohan Mehta',
        authorGradient: 'from-sky-500 to-cyan-600',
        rating: 5,
        daysAgo: 32,
        text: 'Only person I trust above 15,000 ft. Knows exactly how gear behaves in that cold.',
      },
    ],
    occupiedDates: [4, 5, 6, 7, 18, 19, 20].map(isoFromToday),
  },
  {
    id: 'p7',
    name: 'Farhan Qureshi',
    handle: '@farhanstreets',
    gradient: 'from-amber-500 to-yellow-600',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    bio: 'Street and documentary work along the ghats. Available as fixer and shooter for crews new to the city.',
    specialties: ['Documentary', 'Street', 'Candid'],
    proficiency: 'Intermediate',
    dayRate: 7000,
    rating: 4.6,
    timesHired: 31,
    assignmentCount: 35,
    followers: 1240,
    respondsIn: 'under 5 hrs',
    equipment: [
      { category: 'Cameras', items: ['Leica Q3', 'Sony A7C'] },
      { category: 'Lenses', items: ['28mm fixed', '35mm f/1.8', '55mm f/1.8'] },
    ],
    recentWork: [
      { id: 'w1', title: 'Ganga Aarti', gradient: 'from-orange-500 to-red-600' },
      { id: 'w2', title: 'Ghat Mornings', gradient: 'from-yellow-500 to-amber-600' },
      { id: 'w3', title: 'Weavers of BHU', gradient: 'from-indigo-500 to-blue-700' },
      { id: 'w4', title: 'Holi Frames', gradient: 'from-pink-500 to-fuchsia-600' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Priya Nambiar',
        authorGradient: 'from-emerald-500 to-teal-600',
        rating: 5,
        daysAgo: 19,
        text: 'Got us access to rooftops and homes no outsider gets into. Worth every rupee.',
      },
    ],
    occupiedDates: [3, 10, 11, 12, 26].map(isoFromToday),
  },
  {
    id: 'p8',
    name: 'Ishita Bose',
    handle: '@ishitaproduct',
    gradient: 'from-violet-500 to-purple-600',
    city: 'Bengaluru',
    state: 'Karnataka',
    bio: 'Product and food photographer with a compact travel studio. Turns around edits within 48 hours.',
    specialties: ['Product', 'Food', 'Commercial'],
    proficiency: 'Advanced',
    dayRate: 15500,
    rating: 4.7,
    timesHired: 37,
    assignmentCount: 40,
    followers: 2050,
    respondsIn: 'under 2 hrs',
    equipment: [
      { category: 'Cameras', items: ['Sony A7R V'] },
      { category: 'Lenses', items: ['90mm macro', '24-70mm f/2.8', '35mm f/1.4'] },
      { category: 'Lighting', items: ['Godox AD300 x2', 'Light table', 'Diffusion panels'] },
    ],
    recentWork: [
      { id: 'w1', title: 'Coffee Brand Set', gradient: 'from-amber-600 to-yellow-700' },
      { id: 'w2', title: 'Skincare Launch', gradient: 'from-teal-500 to-emerald-600' },
      { id: 'w3', title: 'Menu Shoot', gradient: 'from-red-500 to-orange-600' },
      { id: 'w4', title: 'Watch Macro', gradient: 'from-zinc-500 to-slate-700' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Simran Kaur',
        authorGradient: 'from-fuchsia-500 to-pink-600',
        rating: 5,
        daysAgo: 27,
        text: 'Brought her own light table to a hotel room and made it look like a studio. Problem solver.',
      },
    ],
    occupiedDates: [1, 2, 14, 15, 21, 22].map(isoFromToday),
  },
]

/** The signed-in user — same shape as everyone else, since they both hire and get hired. */
export const currentUser: Photographer = {
  id: 'me',
  name: 'Ashish More',
  handle: '@ashishframes',
  gradient: 'from-indigo-500 to-blue-600',
  city: 'Pune',
  state: 'Maharashtra',
  bio: 'Travel and wedding photographer covering assignments pan India. I hire second shooters on the road and take on work when my calendar is open.',
  specialties: ['Wedding', 'Travel', 'Candid'],
  proficiency: 'Advanced',
  dayRate: 16000,
  rating: 4.8,
  timesHired: 34,
  assignmentCount: 47,
  followers: 2890,
  respondsIn: 'under 1 hr',
  equipment: [
    { category: 'Cameras', items: ['Sony A7 IV', 'Sony A6700 (backup)'] },
    { category: 'Lenses', items: ['24-70mm f/2.8', '70-200mm f/2.8', '35mm f/1.4'] },
    { category: 'Drones', items: ['DJI Air 3'] },
    { category: 'Lighting', items: ['Godox AD200 x2', 'Portable softbox'] },
  ],
  recentWork: [
    { id: 'w1', title: 'Coorg Wedding', gradient: 'from-emerald-500 to-green-700' },
    { id: 'w2', title: 'Konkan Coast', gradient: 'from-blue-500 to-cyan-600' },
    { id: 'w3', title: 'Pune Studio Day', gradient: 'from-violet-500 to-purple-600' },
    { id: 'w4', title: 'Spiti Road Trip', gradient: 'from-orange-500 to-amber-700' },
  ],
  reviews: [
    {
      id: 'r1',
      author: 'Devansh Kapoor',
      authorGradient: 'from-orange-500 to-red-600',
      rating: 5,
      daysAgo: 8,
      text: 'Clear briefs, pays on time, and actually credits his second shooters. Rare combination.',
    },
    {
      id: 'r2',
      author: 'Ishita Bose',
      authorGradient: 'from-violet-500 to-purple-600',
      rating: 5,
      daysAgo: 35,
      text: 'Stepped onto my commercial shoot as backup and matched my edit style without being asked.',
    },
  ],
  occupiedDates: [0, 1, 2, 9, 10, 16, 17, 23].map(isoFromToday),
}

export const initialAssignments: Assignment[] = [
  {
    id: 'a1',
    ownerId: 'me',
    name: 'Kapoor Wedding — Udaipur',
    location: 'Udaipur, Rajasthan',
    description: 'Three-day destination wedding. Need a second shooter for the mandap and a drone operator for the baraat.',
    startDate: isoFromToday(14),
    durationDays: 3,
    startTime: '06:00',
    durationHours: 8,
    approved: true,
    participantIds: ['p1', 'p5'],
    // Nobody is on all three days: Ananya shoots the mehendi and the wedding
    // morning, and Simran covers the sangeet evening in between.
    shifts: {
      p1: [
        { date: isoFromToday(14), startTime: '06:00', durationHours: 8 },
        { date: isoFromToday(16), startTime: '06:00', durationHours: 8 },
      ],
      p5: [{ date: isoFromToday(15), startTime: '16:00', durationHours: 6 }],
    },
    roles: { me: 'Owner', p1: 'Candid Photographer', p5: 'Candid Photographer' },
    invites: { p1: 'accepted', p5: 'awaited' },
  },
  {
    id: 'a2',
    ownerId: 'me',
    name: 'Coastline Travel Feature',
    location: 'Gokarna, Karnataka',
    description: 'Editorial travel feature for a magazine. Aerial coverage plus ground stills across four beaches.',
    startDate: isoFromToday(28),
    durationDays: 5,
    startTime: '08:30',
    durationHours: 6,
    approved: false,
    participantIds: ['p2', 'p3'],
    // Aerials are done in the first two days; the ground stills follow after.
    shifts: {
      p2: [
        { date: isoFromToday(28), startTime: '08:30', durationHours: 6 },
        { date: isoFromToday(29), startTime: '08:30', durationHours: 6 },
      ],
      p3: [
        { date: isoFromToday(30), startTime: '08:30', durationHours: 6 },
        { date: isoFromToday(31), startTime: '08:30', durationHours: 6 },
        { date: isoFromToday(32), startTime: '08:30', durationHours: 6 },
      ],
    },
    roles: { me: 'Owner', p2: 'Drone Pilot', p3: 'Candid Photographer' },
    // Priya passed on this one. She keeps her seat in the group chat regardless.
    invites: { p2: 'accepted', p3: 'rejected' },
  },
  // Anchored to today so the schedule always opens on a week with something in it.
  {
    id: 'a3',
    ownerId: 'me',
    name: "Ridhita's Birthday",
    location: 'Lemon Tree Hotel, Aurangabad',
    description: 'Evening celebration — candid coverage through the cake cutting and the after-party.',
    startDate: isoFromToday(0),
    durationDays: 1,
    startTime: '19:00',
    durationHours: 4,
    approved: false,
    participantIds: ['p2', 'p3'],
    // One day, two call times — Rohan covers the evening, Priya comes in for the
    // cake cutting and stays through the after-party.
    shifts: {
      p2: [{ date: isoFromToday(0), startTime: '19:00', durationHours: 4 }],
      p3: [{ date: isoFromToday(0), startTime: '21:00', durationHours: 3 }],
    },
    roles: { me: 'Owner', p2: 'Candid Photographer', p3: 'Assistant' },
    invites: { p2: 'accepted', p3: 'accepted' },
  },
  {
    id: 'a4',
    ownerId: 'me',
    name: 'Sunrise Editorial — Lonavala',
    location: 'Lonavala, Maharashtra',
    description: 'Golden hour lifestyle set for a apparel lookbook. Two looks before the light goes.',
    startDate: isoFromToday(2),
    durationDays: 1,
    startTime: '05:45',
    durationHours: 3,
    approved: true,
    participantIds: ['p4'],
    // Empty means what it says: everyone is on for the whole shoot.
    shifts: {},
    roles: { me: 'Owner', p4: 'Cinematographer' },
    invites: { p4: 'accepted' },
  },
  // Assignments someone else runs and invited the signed-in user onto. Being
  // booked by another photographer locks that day to Occupied.
  {
    id: 'a5',
    ownerId: 'p1',
    name: 'Deshmukh Reception — Pune',
    location: 'Conrad Pune, Maharashtra',
    // Ananya pinned the hotel itself — a big venue where "Conrad Pune" alone
    // would still leave the crew circling for the right entrance.
    mapUrl: 'https://www.google.com/maps/place/Conrad+Pune/@18.5289,73.876,17z',
    description: 'Reception coverage. Ananya is running the shoot and needs a second shooter on the stage.',
    startDate: isoFromToday(4),
    durationDays: 1,
    startTime: '18:00',
    durationHours: 6,
    approved: true,
    participantIds: ['me', 'p5'],
    // The user comes in an hour after the crew call — the stage work starts late.
    shifts: {
      me: [{ date: isoFromToday(4), startTime: '19:00', durationHours: 5 }],
      p5: [{ date: isoFromToday(4), startTime: '18:00', durationHours: 6 }],
    },
    roles: { p1: 'Owner', me: 'Candid Photographer', p5: 'Assistant' },
    invites: { me: 'accepted', p5: 'accepted' },
  },
  {
    id: 'a6',
    ownerId: 'p4',
    name: 'Monsoon Brand Film — Mahabaleshwar',
    location: 'Mahabaleshwar, Maharashtra',
    description: 'Two-day brand film. Rohan is directing; stills coverage across both days.',
    startDate: isoFromToday(9),
    durationDays: 2,
    startTime: '07:00',
    durationHours: 9,
    approved: false,
    participantIds: ['me'],
    shifts: {},
    roles: { p4: 'Owner', me: 'Candid Photographer' },
    // The one invite still on the signed-in user's plate — this is what the
    // "added you to an assignment" notification opens onto.
    invites: { me: 'awaited' },
  },
]

/** Seeded ids are fixed, so a miss is a broken seed rather than a runtime case. */
function seeded(id: string): Assignment {
  const found = initialAssignments.find((a) => a.id === id)
  if (!found) throw new Error(`Unknown seeded assignment: ${id}`)
  return found
}

// a3 is anchored to today on purpose, so there is always a shoot to remind about.
const todaysShoot = seeded('a3')
const invitedShoot = seeded('a6')
const earlierInvite = seeded('a5')

/**
 * The bell feed, newest first. Every entry points at something that actually
 * exists in the mock — a shoot, a thread, a photographer — so no row is a dead
 * end. Unread chat gets a notification per thread rather than one lumped count,
 * which is what makes it actionable.
 */
export const notifications: AppNotification[] = [
  {
    id: 'n1',
    kind: 'message',
    actorId: 'p4',
    title: 'sent you 2 messages',
    detail: 'Sending the drone footage tonight once it finishes exporting.',
    to: '/chat/c1',
    minutesAgo: 4,
    read: false,
  },
  {
    id: 'n2',
    kind: 'reminder',
    title: `Call time ${formatTime12(todaysShoot.startTime)} today`,
    detail: `${todaysShoot.name} · ${todaysShoot.location}`,
    to: `/assignment/${todaysShoot.id}`,
    minutesAgo: 25,
    read: false,
  },
  {
    id: 'n3',
    kind: 'message',
    actorId: 'p1',
    title: 'sent you a message',
    detail: 'Udaipur works for me. Should I book the 14th to the 17th?',
    to: '/chat/c2',
    minutesAgo: 38,
    read: false,
  },
  {
    id: 'n4',
    kind: 'reminder',
    title: 'Crew sign-off still pending',
    detail: `${todaysShoot.name} is unapproved with ${todaysShoot.participantIds.length} on the crew`,
    to: `/assignment/${todaysShoot.id}`,
    minutesAgo: 95,
    read: false,
  },
  {
    id: 'n5',
    kind: 'assignment',
    actorId: 'p4',
    title: 'added you to an assignment',
    detail: `${invitedShoot.name} · ${invitedShoot.roles.me}`,
    assignmentId: invitedShoot.id,
    to: `/assignment/${invitedShoot.id}`,
    minutesAgo: 300,
    read: false,
  },
  {
    id: 'n6',
    kind: 'comment',
    actorId: 'p3',
    title: 'commented on your post',
    detail: 'The light on the third frame is unreal. What were you shooting at?',
    to: '/photographer/p3',
    minutesAgo: 480,
    read: true,
  },
  {
    id: 'n7',
    kind: 'follow',
    actorId: 'p7',
    title: 'started following you',
    to: '/photographer/p7',
    minutesAgo: 1500,
    read: true,
  },
  {
    id: 'n8',
    kind: 'assignment',
    actorId: 'p1',
    title: 'added you to an assignment',
    detail: `${earlierInvite.name} · ${earlierInvite.roles.me}`,
    assignmentId: earlierInvite.id,
    to: `/assignment/${earlierInvite.id}`,
    minutesAgo: 2900,
    read: true,
  },
  {
    id: 'n9',
    kind: 'follow',
    actorId: 'p8',
    title: 'started following you',
    to: '/photographer/p8',
    minutesAgo: 4300,
    read: true,
  },
]

/**
 * Opening exchanges in each assignment's group chat, keyed by assignment id.
 * Every sender is a member of that assignment — the owner or someone on its
 * crew — so the group renders their name and avatar. Assignments created in the
 * app start with an empty chat instead.
 */
export const assignmentChatSeeds: Record<string, { unread: number; messages: Message[] }> = {
  // Kapoor Wedding — me (owner) and Ananya Rao.
  a1: {
    unread: 2,
    messages: [
      { id: 'g1m1', from: 'me', text: 'Run sheet for all three days is coming tonight. Mandap coverage is the priority on day two.', minutesAgo: 2880 },
      { id: 'g1m2', from: 'p1', text: "Got it. I'll take the mandap from the east side, the light is better before 9.", minutesAgo: 2760 },
      { id: 'g1m3', from: 'me', text: 'Still waiting on a drone operator for the baraat. Will confirm this week.', minutesAgo: 1500 },
      { id: 'g1m4', from: 'p1', text: 'The family wants a group frame with all the cousins on day one. Budget 20 minutes for it.', minutesAgo: 900 },
      { id: 'g1m5', from: 'p1', text: 'Bringing the 85mm for couple portraits after the pheras.', minutesAgo: 240 },
    ],
  },

  // Coastline Travel Feature — me (owner), Rohan Mehta on aerials. Priya Nambiar
  // declined the invite and is still in here, which is the point of the rule.
  a2: {
    unread: 1,
    messages: [
      { id: 'g2m1', from: 'me', text: 'Holding five days for this. The magazine wants aerials plus ground stills across four beaches.', minutesAgo: 4320 },
      { id: 'g2m2', from: 'p2', text: "I'm in for the aerials. There's a no-fly pocket near the temple, I'll map a route around it.", minutesAgo: 4000 },
      { id: 'g2m3', from: 'p3', text: 'Had to pass on this one, I am already booked that week. Shout if the dates move.', minutesAgo: 3600 },
      { id: 'g2m4', from: 'p2', text: 'Sending a drone shot list once I have the tide timings for that week.', minutesAgo: 900 },
    ],
  },

  // Ridhita's Birthday — me (owner), Rohan Mehta, Priya Nambiar.
  a3: {
    unread: 0,
    messages: [
      { id: 'g3m1', from: 'me', text: 'Cake cutting is at 9, so we should be fully set up by 8:15.', minutesAgo: 600 },
      { id: 'g3m2', from: 'p2', text: "I'll be there by 7:45 with the lights.", minutesAgo: 480 },
      { id: 'g3m3', from: 'p3', text: 'Carrying spare batteries and the reflector kit.', minutesAgo: 300 },
      { id: 'g3m4', from: 'p2', text: 'Parking is tight at the venue — come in from the back gate.', minutesAgo: 45 },
    ],
  },

  // Sunrise Editorial — me (owner) and Devansh Kapoor.
  a4: {
    unread: 0,
    messages: [
      { id: 'g4m1', from: 'me', text: 'Call time 5:45, sunrise is 6:20. We get one shot at this light.', minutesAgo: 1440 },
      { id: 'g4m2', from: 'p4', text: 'On site by 5:30 with the gimbal.', minutesAgo: 1200 },
      { id: 'g4m3', from: 'me', text: 'Two looks, changes happen in the car. Keep it moving.', minutesAgo: 900 },
      { id: 'g4m4', from: 'p4', text: 'Forecast is clear. I will do a quick recce the evening before so we are not scouting at 5am.', minutesAgo: 420 },
      { id: 'g4m5', from: 'p4', text: 'Bringing a reflector for fill — the sun comes in hard off the valley.', minutesAgo: 180 },
    ],
  },

  // Deshmukh Reception — Ananya Rao runs it; I am crew alongside Simran Kaur.
  a5: {
    unread: 1,
    messages: [
      { id: 'g5m1', from: 'p1', text: 'Adding you both — reception is on the 12th at Conrad Pune.', minutesAgo: 5760 },
      { id: 'g5m2', from: 'p1', text: 'Ashish, you have the stage. Simran, candids on the floor.', minutesAgo: 5700 },
      { id: 'g5m3', from: 'me', text: 'Works for me. Bringing the 70-200 for stage coverage.', minutesAgo: 4200 },
      { id: 'g5m4', from: 'p5', text: 'Same here, I will keep to available light on the floor.', minutesAgo: 3000 },
    ],
  },

  // Monsoon Brand Film — Devansh Kapoor runs it; I am the stills shooter.
  a6: {
    unread: 0,
    messages: [
      { id: 'g6m1', from: 'p4', text: 'Two days, stills across both. Client wants the monsoon look so we shoot rain or shine.', minutesAgo: 8640 },
      { id: 'g6m2', from: 'me', text: 'Noted. Packing rain covers for everything.', minutesAgo: 7000 },
      { id: 'g6m3', from: 'p4', text: 'Moodboard is with you — look at frames 4 through 9 especially.', minutesAgo: 1800 },
    ],
  },
}

/** Ordered most recent first — the home rail slices the head, the chat tab lists them all. */
export const conversations: Conversation[] = [
  {
    id: 'c1',
    kind: 'direct',
    photographerId: 'p4',
    unread: 2,
    messages: [
      { id: 'm1', from: 'me', text: 'Are we still on for the Gokarna leg?', minutesAgo: 240 },
      { id: 'm2', from: 'them', text: 'Yes, flying down on the 3rd.', minutesAgo: 180 },
      {
        id: 'm3',
        from: 'them',
        text: 'Sending the drone footage tonight once it finishes exporting.',
        minutesAgo: 4,
      },
    ],
  },
  {
    id: 'c2',
    kind: 'direct',
    photographerId: 'p1',
    unread: 1,
    messages: [
      {
        id: 'm1',
        from: 'me',
        text: 'Sharing the Kapoor wedding brief — three days, mandap plus baraat.',
        minutesAgo: 600,
      },
      { id: 'm2', from: 'them', text: 'Looks good. My rate is 18k a day plus travel.', minutesAgo: 520 },
      { id: 'm3', from: 'me', text: 'Works for me. Dates are the 14th onward.', minutesAgo: 450 },
      {
        id: 'm4',
        from: 'them',
        text: 'Udaipur works for me. Should I book the 14th to the 17th?',
        minutesAgo: 38,
      },
    ],
  },
  {
    id: 'c3',
    kind: 'direct',
    photographerId: 'p6',
    unread: 0,
    messages: [
      {
        id: 'm1',
        from: 'me',
        text: 'Looking for someone who shoots cold-weather landscapes.',
        minutesAgo: 400,
      },
      {
        id: 'm2',
        from: 'them',
        text: 'Shared my Ladakh set — let me know if the tone matches your edit.',
        minutesAgo: 145,
      },
    ],
  },
  {
    id: 'c4',
    kind: 'direct',
    photographerId: 'p2',
    unread: 0,
    messages: [
      { id: 'm1', from: 'me', text: 'Budget is 15k a day for two days, does that work?', minutesAgo: 520 },
      { id: 'm2', from: 'them', text: 'Day rate is fine. I usually invoice 50% upfront.', minutesAgo: 400 },
    ],
  },
  {
    id: 'c5',
    kind: 'direct',
    photographerId: 'p8',
    unread: 0,
    messages: [
      { id: 'm1', from: 'me', text: 'Credited you on the commercial set that went live.', minutesAgo: 1600 },
      { id: 'm2', from: 'them', text: 'Thanks for the credit on the commercial shoot!', minutesAgo: 1500 },
    ],
  },
  {
    id: 'c6',
    kind: 'direct',
    photographerId: 'p3',
    unread: 0,
    messages: [
      { id: 'm1', from: 'me', text: 'Holding the weekend of the 20th for a coastal shoot.', minutesAgo: 3000 },
      {
        id: 'm2',
        from: 'them',
        text: 'Blocked out the weekend. Send the brief whenever it is ready.',
        minutesAgo: 2900,
      },
    ],
  },
  {
    id: 'c7',
    kind: 'direct',
    photographerId: 'p5',
    unread: 0,
    messages: [
      { id: 'm1', from: 'me', text: 'Free for a studio day next week?', minutesAgo: 5900 },
      { id: 'm2', from: 'them', text: 'I am travelling till the 20th, can we talk after?', minutesAgo: 5800 },
    ],
  },
  {
    id: 'c8',
    kind: 'direct',
    photographerId: 'p7',
    unread: 0,
    messages: [
      { id: 'm1', from: 'me', text: 'Can you send the raws from the Pune shoot?', minutesAgo: 11200 },
      { id: 'm2', from: 'them', text: 'Added you on the shared drive for the raw files.', minutesAgo: 11000 },
    ],
  },
]

/** Stand-in for a photo library — the composers pick from these instead of uploading. */
export const SAMPLE_PHOTOS = [
  { id: 'sp1', label: 'Golden hour', src: weddingGoldenHour },
  { id: 'sp2', label: 'Coastline', src: coastlineSunrise },
  { id: 'sp3', label: 'High altitude', src: mountainsDusk },
  { id: 'sp4', label: 'Monsoon green', src: forestMonsoon },
  { id: 'sp5', label: 'Blue hour', src: resortDusk },
]

/** The home feed, newest first. */
export const posts: Post[] = [
  {
    id: 'po1',
    photographerId: 'p1',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption:
      'Last of the light at the haveli. No reflector, no flash — just the sun dropping behind them at exactly the right minute.',
    likes: 480,
    comments: 56,
    postedOn: isoFromToday(-2),
  },
  {
    id: 'po2',
    photographerId: 'p4',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Took the drone up over the coastline before the mist burned off. Worth the 4am alarm.',
    likes: 1264,
    comments: 89,
    postedOn: isoFromToday(-5),
  },
  {
    id: 'po3',
    photographerId: 'p6',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption:
      'Ladakh in January. Minus eighteen, three batteries taped to my chest to keep them alive, and a sky that made all of it reasonable.',
    likes: 872,
    comments: 41,
    postedOn: isoFromToday(-9),
  },
  {
    id: 'po4',
    photographerId: 'p3',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Scouted the plantation trail for next week’s monsoon shoot. Shot wide open, let the light do the rest.',
    likes: 317,
    comments: 22,
    postedOn: isoFromToday(-14),
  },
  {
    id: 'po5',
    photographerId: 'p2',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption:
      'Resort campaign wrapped. Six setups, one afternoon, and a client who let me keep the blue hour slot free.',
    likes: 654,
    comments: 37,
    postedOn: isoFromToday(-21),
  },
  // Older half of the feed. Every photographer carries three posts so their
  // profile grid — and the "See all" gallery behind it — has something to show.
  {
    id: 'po6',
    photographerId: 'me',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'First morning of the Mahabaleshwar recce. Everything still wet, everything still green.',
    likes: 96,
    comments: 8,
    postedOn: isoFromToday(-26),
  },
  {
    id: 'po7',
    photographerId: 'p5',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'Editorial test with a borrowed 85mm. Backlight does most of the styling for you.',
    likes: 743,
    comments: 44,
    postedOn: isoFromToday(-28),
  },
  {
    id: 'po8',
    photographerId: 'p1',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Sangeet venue the night before, empty. I shoot every room before the guests fill it.',
    likes: 512,
    comments: 29,
    postedOn: isoFromToday(-33),
  },
  {
    id: 'po9',
    photographerId: 'p7',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Two hours off the ghat road, following a path because it looked like it went somewhere.',
    likes: 289,
    comments: 19,
    postedOn: isoFromToday(-37),
  },
  {
    id: 'po10',
    photographerId: 'p6',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Came down from the mountains for a week. Sea level felt like breathing through a straw in reverse.',
    likes: 605,
    comments: 31,
    postedOn: isoFromToday(-41),
  },
  {
    id: 'po11',
    photographerId: 'me',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Property shoot in Alibaug. Held the last frame until the pool lights took over from the sky.',
    likes: 141,
    comments: 12,
    postedOn: isoFromToday(-45),
  },
  {
    id: 'po12',
    photographerId: 'p8',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Hospitality client, full day. Product habits transfer better to interiors than people think.',
    likes: 388,
    comments: 23,
    postedOn: isoFromToday(-49),
  },
  {
    id: 'po13',
    photographerId: 'p3',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'Documentary work took me far from the backwaters this month. No complaints.',
    likes: 421,
    comments: 26,
    postedOn: isoFromToday(-54),
  },
  {
    id: 'po14',
    photographerId: 'p4',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'Jaipur, 43 degrees, and they still wanted the outdoor portraits. We waited for six o’clock.',
    likes: 967,
    comments: 61,
    postedOn: isoFromToday(-58),
  },
  {
    id: 'po15',
    photographerId: 'p2',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'North Goa before the season starts. Twenty minutes of this a day, and then it is gone.',
    likes: 1103,
    comments: 74,
    postedOn: isoFromToday(-62),
  },
  {
    id: 'po16',
    photographerId: 'me',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'Sahyadris at dusk, shot from the assignment I nearly turned down. Glad I did not.',
    likes: 187,
    comments: 15,
    postedOn: isoFromToday(-66),
  },
  {
    id: 'po17',
    photographerId: 'p5',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Lookbook location scout. Kept the cabanas for the second half of the shoot.',
    likes: 534,
    comments: 33,
    postedOn: isoFromToday(-71),
  },
  {
    id: 'po18',
    photographerId: 'p1',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Pre-wedding, no venue, no décor. Just a trail and two people who trusted the plan.',
    likes: 618,
    comments: 47,
    postedOn: isoFromToday(-75),
  },
  {
    id: 'po19',
    photographerId: 'p3',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Turtle nesting survey, day nine. Mostly waiting, occasionally this.',
    likes: 356,
    comments: 28,
    postedOn: isoFromToday(-80),
  },
  {
    id: 'po20',
    photographerId: 'p6',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Lower altitude, denser air, greener everything. A useful reset between expeditions.',
    likes: 497,
    comments: 24,
    postedOn: isoFromToday(-84),
  },
  {
    id: 'po21',
    photographerId: 'p4',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Corporate offsite, last evening. The brief said "candid", so I stayed out of the way.',
    likes: 402,
    comments: 21,
    postedOn: isoFromToday(-89),
  },
  {
    id: 'po22',
    photographerId: 'p7',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'A ghat wedding at first light. Street habits, one lens, no direction given.',
    likes: 465,
    comments: 38,
    postedOn: isoFromToday(-93),
  },
  {
    id: 'po23',
    photographerId: 'p8',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Sourcing shoot for a tea client. Studio lighting cannot fake this, so we drove.',
    likes: 274,
    comments: 17,
    postedOn: isoFromToday(-97),
  },
  {
    id: 'po24',
    photographerId: 'p2',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'Flew the drone higher than I usually dare. The valley filled with cloud while I was up there.',
    likes: 889,
    comments: 52,
    postedOn: isoFromToday(-102),
  },
  {
    id: 'po25',
    photographerId: 'p5',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'Winterwear campaign, shot on location instead of in the studio. The client took some convincing.',
    likes: 812,
    comments: 49,
    postedOn: isoFromToday(-106),
  },
  {
    id: 'po26',
    photographerId: 'p7',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Assisted on a hotel job to pay for a month of personal work. An honest trade.',
    likes: 198,
    comments: 14,
    postedOn: isoFromToday(-110),
  },
  {
    id: 'po27',
    photographerId: 'p8',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Packaging shoot moved outdoors at the last minute. Sunrise is a very cheap softbox.',
    likes: 331,
    comments: 20,
    postedOn: isoFromToday(-114),
  },
  // The back catalogue. Six posts each is enough for a profile grid to read as a
  // body of work rather than a placeholder.
  {
    id: 'po28',
    photographerId: 'me',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'Second shooter on a Nashik wedding. Stood where nobody was looking and let the light arrive.',
    likes: 164,
    comments: 11,
    postedOn: isoFromToday(-118),
  },
  {
    id: 'po29',
    photographerId: 'p1',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'Destination wedding recce in Himachal. Told them the ceremony has to end by five.',
    likes: 723,
    comments: 45,
    postedOn: isoFromToday(-122),
  },
  {
    id: 'po30',
    photographerId: 'p2',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Inland from the beaches for once. Canopy this thick, the drone stays in the bag.',
    likes: 576,
    comments: 30,
    postedOn: isoFromToday(-126),
  },
  {
    id: 'po31',
    photographerId: 'p3',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Hornbill survey, third season running. Same trail, entirely different forest each year.',
    likes: 448,
    comments: 34,
    postedOn: isoFromToday(-130),
  },
  {
    id: 'po32',
    photographerId: 'p4',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Client flew the whole event to the coast. I flew with it and got one morning to myself.',
    likes: 612,
    comments: 35,
    postedOn: isoFromToday(-134),
  },
  {
    id: 'po33',
    photographerId: 'p5',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Resort-wear story, shot deep in the plantation. Green on green on green.',
    likes: 691,
    comments: 42,
    postedOn: isoFromToday(-138),
  },
  {
    id: 'po34',
    photographerId: 'p6',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'Six days out on the Markha valley trail. This was the evening that paid for the rest.',
    likes: 1042,
    comments: 63,
    postedOn: isoFromToday(-142),
  },
  {
    id: 'po35',
    photographerId: 'p7',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Left the river for the sea for two weeks. Different water, same habit of waiting.',
    likes: 236,
    comments: 16,
    postedOn: isoFromToday(-146),
  },
  {
    id: 'po36',
    photographerId: 'p8',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'Jewellery campaign with real couples instead of models. Far better hands, far less direction.',
    likes: 409,
    comments: 25,
    postedOn: isoFromToday(-150),
  },
  {
    id: 'po37',
    photographerId: 'me',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Drove down to Ganpatipule at 3am on a hunch. The hunch was right.',
    likes: 208,
    comments: 18,
    postedOn: isoFromToday(-154),
  },
  {
    id: 'po38',
    photographerId: 'p1',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Beach ceremony, barefoot, forty guests. My favourite kind of brief.',
    likes: 834,
    comments: 58,
    postedOn: isoFromToday(-158),
  },
  {
    id: 'po39',
    photographerId: 'p2',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'Aerials for a wedding film, then this from the ground while the crew packed up.',
    likes: 758,
    comments: 41,
    postedOn: isoFromToday(-162),
  },
  {
    id: 'po40',
    photographerId: 'p3',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Conservation piece on coastal development. Not every frame in the story is an accusation.',
    likes: 302,
    comments: 27,
    postedOn: isoFromToday(-166),
  },
  {
    id: 'po41',
    photographerId: 'p4',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Product day for an outdoor brand. Carried the whole kit up the trail and used one lens.',
    likes: 385,
    comments: 22,
    postedOn: isoFromToday(-170),
  },
  {
    id: 'po42',
    photographerId: 'p5',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'Swim editorial, first light, nobody else on the sand. Worth the call time.',
    likes: 927,
    comments: 55,
    postedOn: isoFromToday(-174),
  },
  {
    id: 'po43',
    photographerId: 'p6',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Property job in Goa between expeditions. Sea level pays better than altitude.',
    likes: 486,
    comments: 23,
    postedOn: isoFromToday(-178),
  },
  {
    id: 'po44',
    photographerId: 'p7',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'A month photographing a family that migrates with the season. This was where they stopped.',
    likes: 512,
    comments: 47,
    postedOn: isoFromToday(-182),
  },
  {
    id: 'po45',
    photographerId: 'p8',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'Location plates for a campaign backdrop. Shot to be composited, good enough to stand alone.',
    likes: 264,
    comments: 15,
    postedOn: isoFromToday(-186),
  },
  {
    id: 'po46',
    photographerId: 'me',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'My first paid wedding. Kept this one frame and deleted most of the rest, honestly.',
    likes: 132,
    comments: 21,
    postedOn: isoFromToday(-190),
  },
  {
    id: 'po47',
    photographerId: 'p1',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'Ten minutes between the ceremony and the reception is enough, if you have scouted the spot.',
    likes: 1188,
    comments: 79,
    postedOn: isoFromToday(-194),
  },
  {
    id: 'po48',
    photographerId: 'p2',
    image: resortDusk,
    alt: 'Poolside cabanas at a beach resort under a violet dusk sky',
    caption: 'Same resort, third year running. They keep booking the same slot and I keep taking it.',
    likes: 543,
    comments: 26,
    postedOn: isoFromToday(-198),
  },
  {
    id: 'po49',
    photographerId: 'p3',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'A friend asked and I said yes. Wildlife patience turns out to transfer to weddings.',
    likes: 397,
    comments: 33,
    postedOn: isoFromToday(-202),
  },
  {
    id: 'po50',
    photographerId: 'p4',
    image: mountainsDusk,
    alt: 'Snow-capped peaks rising above a valley filled with cloud at dusk',
    caption: 'Two days off in the middle of a fourteen-day event calendar. Spent both up here.',
    likes: 671,
    comments: 38,
    postedOn: isoFromToday(-206),
  },
  {
    id: 'po51',
    photographerId: 'p5',
    image: weddingGoldenHour,
    alt: 'Couple backlit by golden hour light, the bride holding a bouquet',
    caption: 'Bridal editorial for a magazine cover. The bouquet was the art director’s idea, and she was right.',
    likes: 1054,
    comments: 68,
    postedOn: isoFromToday(-210),
  },
  {
    id: 'po52',
    photographerId: 'p6',
    image: coastlineSunrise,
    alt: 'Turquoise surf washing onto an empty beach at sunrise',
    caption: 'The first time I saw the sea. Thirty-one years old, and I shot two hundred frames of nothing.',
    likes: 1361,
    comments: 96,
    postedOn: isoFromToday(-214),
  },
  {
    id: 'po53',
    photographerId: 'p7',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Walked out of the city for a day to remember what quiet sounds like.',
    likes: 221,
    comments: 13,
    postedOn: isoFromToday(-218),
  },
  {
    id: 'po54',
    photographerId: 'p8',
    image: forestMonsoon,
    alt: 'Sunlit path winding through a dense green forest',
    caption: 'Estate visit for a coffee brand. Spent longer talking to the growers than shooting.',
    likes: 318,
    comments: 24,
    postedOn: isoFromToday(-222),
  },
]

export const ALL_CITIES = Array.from(new Set(photographers.map((p) => p.city))).sort()

export const ALL_SPECIALTIES = Array.from(
  new Set(photographers.flatMap((p) => p.specialties)),
).sort()

const minutesAgo = (m: number) => Date.now() - m * 60_000
const nameOf = (id: string) => photographers.find((p) => p.id === id)?.name ?? 'Someone'

/**
 * What the user has already done, so the log opens with history rather than a
 * blank page. Anything they do from here on is appended live.
 */
export const initialActivity: ActivityEntry[] = [
  {
    id: 'ac1',
    kind: 'assignment',
    title: `Created "${initialAssignments[2].name}"`,
    detail: initialAssignments[2].location,
    to: `/assignment/${initialAssignments[2].id}`,
    at: minutesAgo(140),
  },
  {
    id: 'ac2',
    kind: 'like',
    title: `Liked a photo by ${nameOf('p6')}`,
    to: '/',
    at: minutesAgo(320),
  },
  {
    id: 'ac3',
    kind: 'save',
    title: `Saved ${nameOf('p2')}`,
    detail: 'Kept for a future assignment',
    to: '/photographer/p2',
    at: minutesAgo(1_500),
  },
  {
    id: 'ac4',
    kind: 'follow',
    title: `Followed ${nameOf('p5')}`,
    to: '/photographer/p5',
    at: minutesAgo(2_600),
  },
  {
    id: 'ac5',
    kind: 'post',
    title: 'Published a photo',
    detail: 'Backwaters at first light',
    to: '/profile/posts',
    at: minutesAgo(4_100),
  },
  {
    id: 'ac6',
    kind: 'follow',
    title: `Followed ${nameOf('p1')}`,
    to: '/photographer/p1',
    at: minutesAgo(9_800),
  },
]

/** Accounts already on the device. The signed-in one is the current user. */
export const initialLinkedAccounts: LinkedAccount[] = [
  {
    id: 'acc-studio',
    name: 'More Studio',
    handle: '@morestudio.co',
    gradient: 'from-emerald-500 to-teal-600',
  },
]

export const initialNotificationPrefs: NotificationPrefs = {
  invites: true,
  messages: true,
  comments: true,
  follows: false,
  reminders: true,
  emailDigest: false,
  quietHours: true,
}

export const initialPrivacy: PrivacySettings = {
  privateAccount: false,
  showAvailability: true,
  showDayRate: true,
  discoverable: true,
  messagesFrom: 'everyone',
  blockedIds: ['p7'],
}

export const initialVerification: VerificationRequest = {
  status: 'unverified',
  fullName: currentUser.name,
  category: 'Photographer',
  idType: 'Aadhaar',
  portfolio: '',
  note: '',
}
